package semconv

const (
	AttrDeviceID        = "device.id"
	AttrDeviceName      = "device.name"
	AttrDeviceMAC       = "device.mac"
	AttrDeviceModel     = "device.model"
	AttrSiteName        = "site.name"
	AttrTenantID        = "tenant.id"
	AttrNetHostIP       = "net.host.ip"
	AttrVersion         = "version"
	AttrBuild           = "build"
	AttrBuildDate       = "build.date"
	AttrState           = "state"
	AttrLine            = "line"
	AttrLabel           = "label"
	AttrSIPAddress      = "sip_address"
	AttrDirection       = "direction"
	AttrParam           = "param"
	AttrSource          = "source"
	AttrCollectorID     = "collector.id"
	AttrEventName       = "event.name"
	AttrServiceName     = "service.name"
	AttrDurationSeconds = "duration_seconds"

	MetricLensDeviceConnected                = "polylens.device.connected"
	MetricLensDeviceLastDetectedSeconds      = "polylens.device.last_detected_seconds"
	MetricLensDeviceLastConfigRequestSeconds = "polylens.device.last_config_request_seconds"
	MetricLensDeviceFirmwareInfo             = "polylens.device.firmware_info"
	MetricLensDeviceFirmwareCurrent          = "polylens.device.firmware_current"
	MetricLensDeviceActiveCalls              = "polylens.device.active_calls"
	MetricLensStreamConnected                = "polylens.stream.connected"
	MetricPhoneUptimeSeconds                 = "polyphone.uptime_seconds"
	MetricPhoneNetworkPackets                = "polyphone.network.packets"
	MetricPhoneLineRegistered                = "polyphone.line.registered"
	MetricPhoneLinesTotal                    = "polyphone.lines_total"
	MetricPhoneConfigParamSource             = "polyphone.config_param_source"
	MetricPhoneAPIState                      = "polyphone.api_state"
	MetricBuildInfo                          = "polylens2otel.build_info"
	MetricCollectorDuration                  = "polylens2otel.collector.duration"
	MetricCollectorAvailability              = "polylens2otel.collector.availability"
	MetricCollectorExpectedInterval          = "polylens2otel.collector.expected_interval"
	MetricHTTPClientRequestDuration          = "polylens2otel.http.client.request.duration"
	MetricHTTP4xx                            = "polylens2otel.http_4xx"
	MetricHTTP5xx                            = "polylens2otel.http_5xx"
	MetricAPIUnexpected                      = "polylens2otel.api.unexpected"
	MetricAuthTokenRefresh                   = "polylens2otel.auth.token.refresh"         //nolint:gosec // Metric name, not a credential.
	MetricAuthTokenExpiresSeconds            = "polylens2otel.auth.token.expires_seconds" //nolint:gosec // Metric name, not a credential.
	MetricStreamReconnects                   = "polylens2otel.stream.reconnects"
	MetricStreamMessages                     = "polylens2otel.stream.messages"
	MetricStreamLastMessageSeconds           = "polylens2otel.stream.last_message_seconds"
	MetricIngestEmittedPoints                = "polylens2otel.ingest.emitted_points"
	MetricIngestSourceRecords                = "polylens2otel.ingest.source_records"
	MetricCheckpointPersistErrors            = "polylens2otel.checkpoint.persist.errors"
	EventLensCDR                             = "polylens.cdr"
)
