name: actionlint

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions: {}

jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@328bc72e11165b582079d424fd6b551221435250 # retried, checksum-verified installer
