name: actionlint

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions: {}

jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@ff89dc29cee6fbe49128a19715ee3f60390be0dc # v1.9.7
