name: zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions: {}

jobs:
  zizmor:
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: rknightion/.github/.github/workflows/zizmor.yml@65aedb61754e9bf31e947c17409256ba0c58c637 # v1.4.3
